const fs = require('fs-extra');
const { Sequelize } = require('sequelize');
if (fs.existsSync('set.env'))
    require('dotenv').config({ path: __dirname + '/set.env' });
const path = require("path");
const databasePath = path.join(__dirname, './database.db');
const DATABASE_URL = process.env.DATABASE_URL === undefined
    ? databasePath
    : process.env.DATABASE_URL;
module.exports = { session: process.env.SESSION_ID || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMEhFUUFoMmRZK09lNTJHVk5CSGtad09zWTA5V09CeXFpZW5hS00zSWgxVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSGtDZWpWS2tBOVVGUWM5K256d1JVQURxakhFM0dGbFk2cmJHTENzVk1ROD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFQzdmeFJheWNaK0g0YjhJUWlNYTc4MVpqSXpiR3NCL3hJWkhKL0FDVVVzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJQQk9CUjdGL1pxd0ttS0VwOE5GUnk0bHhZUHVYSDkxR0c4ZFR3UzBHVUJJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNMQlNKRkNDTXN2Z1g5dkphQTYrS1VrMG5tWU04Q2tGZDN4OFpvbnB1bnc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlJzN24wbVU5cXptTmx2ZHMyQTNyTjAxa3VjQUIvZUlpY04yZ1NjWHRlWGM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiV0lKbFNiRU44MkRQRFRVWGoxcGJINmZpbkZGVUFCYkN3YVdSUEVDdzdrcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkhvTys3MUxCeUZnaDllcjN6RlFvV3ZzUy84MFFTcy8xYnFhUDcrbTZBcz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlM2R2tTSllKOVlZQm9qUGZ3WmpqSUhaUDRXNW1jSGFCNG5zUnpiemlRWVJEaHVUV3c3TGtldmdGdWlSSWpVeUZ3ODR4MndOckh6QitXWURXUDZrSERnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzAsImFkdlNlY3JldEtleSI6InRQbnBudHoxd2k5R2JVWnk1Z3NtWTN1VHMrRGpNTm1yZXBQdGJLTFUrMWc9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzMTIwNDc5NDUzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkUyQ0U5QjBCODA0RjZEMkU5NjJBM0ZDNDI5QTFGQUZGIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDc2MDM0MDd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkyMzEyMDQ3OTQ1M0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzM0Q2QjkxQkNCNUM3QkNBRDgwQzI5MEFENTQ0MDkzRiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQ3NjAzNDA4fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MjMxMjA0Nzk0NTNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMzExQzczNjkyMjE0QUI0OEJBRTgxNTdBQjQxOEVCNjkifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0NzYwMzQyM30seyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzMTIwNDc5NDUzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6Ijg3MDQyNzdEQkI4QTdBRDBBMzA4REZGQUJFQ0RGMjcxIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDc2MDM0Mjh9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkyMzEyMDQ3OTQ1M0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJENjdFMjhDNzYxMjdBQUMzNkQ2NjQxNDUwQzBGRjRFOSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQ3NjAzNDM0fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5MjMxMjA0Nzk0NTNAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiMEFGMUI1RjEwRDk5NEQ3NjVDMjcwNDYxQUUwNDk2RDYifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc0NzYwMzQ0MH0seyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzMTIwNDc5NDUzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjQ1NkQ3NjczQUM5MDY0RkU4MkNEODM4RTM5NTBEOURBIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDc2MDM0NDV9LHsia2V5Ijp7InJlbW90ZUppZCI6IjkyMzEyMDQ3OTQ1M0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI3NjkxRDczRkIwMTVCNDY3MDQzOUZBOTM2ODU0NzIwMCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzQ3NjAzNDQ5fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiIxMjNMT1RVUyIsIm1lIjp7ImlkIjoiOTIzMTIwNDc5NDUzOjE0QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMTQxMTMzMjYyOTA5NTEwOjE0QGxpZCIsIm5hbWUiOiJBc2FkIE1hbGlrIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMVGt4N0FCRU1HZnFjRUdHQVFnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJobFU0NUkxWlA1NS85Ri9rU1kwZHlvbVk2cGlUbVZwVUtGdkY5S2dTWG1RPSIsImFjY291bnRTaWduYXR1cmUiOiJDV1NMemxFSmNCN2F2bEhkWUJ6UFZiRW5zbk1MOC9ickhtSjlvRVNXU0JGTENCeklKN3loN09sVWFWOWUrNUUwbHV3NTJydGFDVEE5YjY1ODlzWFhDZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoidXEyY0p6T1lpZklhTm9aNEh5SEowM1M4N0pwaksyOXpIeUVjaEdjdGFYNnd0V3F3VlFRemNOZHRUVVNDODg1QVN0UFJQMnlIK1hXblM5SDVBZmM3Q2c9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5MjMxMjA0Nzk0NTM6MTRAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWVpWT09TTldUK2VmL1JmNUVtTkhjcUptT3FZazVsYVZDaGJ4ZlNvRWw1ayJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FJSUNBPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzQ3NjAzNDA1LCJsYXN0UHJvcEhhc2giOiIzUjlaMzkiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUdsViJ9',
    PREFIXE: process.env.PREFIX || ".",
    OWNER_NAME: process.env.OWNER_NAME || "Asad",
    NUMERO_OWNER : process.env.NUMERO_OWNER || "Asad",              
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "yes",
    AUTO_DOWNLOAD_STATUS: process.env.AUTO_DOWNLOAD_STATUS || 'no',
    BOT : process.env.BOT_NAME || 'ASAD',
    URL : process.env.BOT_MENU_LINKS || 'https://telegra.ph/file/17c83719a1b40e02971e4.jpg',
    MODE: process.env.PUBLIC_MODE || "no",
    PM_PERMIT: process.env.PM_PERMIT || 'yes',
    HEROKU_APP_NAME : process.env.HEROKU_APP_NAME,
    HEROKU_APY_KEY : process.env.HEROKU_APY_KEY ,
    WARN_COUNT : process.env.WARN_COUNT || '3' ,
    ETAT : process.env.PRESENCE || '',
    ANTICALL : process.env.ANTICALL || 'yes',   
    AUTO_BIO : process.env.AUTO_BIO || 'yes',               
    DP : process.env.STARTING_BOT_MESSAGE || "yes",
    ANTIDELETE1 : process.env.ANTI_DELETE_MESSAGE || 'yes',
    AUTO_REACT : process.env.AUTO_REACT || 'no',
    AUTO_REACT : process.env.AUTO_REACT || 'no',              
    AUTO_REACT_STATUS : process.env.AUTO_REACT_STATUS || 'yes',
    AUTO_READ : process.env.AUTO_READ || 'yes',
    DATABASE_URL,
    DATABASE: DATABASE_URL === databasePath
        ? "postgresql://postgres:bKlIqoOUWFIHOAhKxRWQtGfKfhGKgmRX@viaduct.proxy.rlwy.net:47738/railway" : "postgresql://postgres:bKlIqoOUWFIHOAhKxRWQtGfKfhGKgmRX@viaduct.proxy.rlwy.net:47738/railway",
   
};
let fichier = require.resolve(__filename);
fs.watchFile(fichier, () => {
    fs.unwatchFile(fichier);
    console.log(`mise à jour ${__filename}`);
    delete require.cache[fichier];
    require(fichier);
});

